import rehypeAutolinkHeadings from "rehype-autolink-headings";
import rehypePrettyCode from "rehype-pretty-code";
import rehypeSlug from "rehype-slug";
import remarkGfm from "remark-gfm";
import type { MDXRemote } from "next-mdx-remote/rsc";

// Derived from MDXRemote's own prop signature rather than a deep
// internal import path, which next-mdx-remote's package.json
// `exports` map doesn't expose as a public subpath.
type SerializeOptions = NonNullable<Parameters<typeof MDXRemote>[0]["options"]>;

/**
 * Compile options shared by every post render.
 *
 * - remarkGfm: tables, strikethrough, task lists, autolinked URLs -
 *   all common in testing documentation (e.g. comparison tables of
 *   tools/frameworks).
 * - rehypeSlug: adds `id` attributes to headings using github-slugger,
 *   matching the IDs generated by `extractTableOfContents` (toc.ts).
 * - rehypeAutolinkHeadings: wraps heading text in a self-link so
 *   readers can copy a direct URL to any section.
 * - rehypePrettyCode: Shiki-powered syntax highlighting rendered at
 *   build time (zero client JS, no flash of unstyled code).
 */
export const mdxOptions: SerializeOptions = {
  mdxOptions: {
    remarkPlugins: [remarkGfm],
    rehypePlugins: [
      rehypeSlug,
      [
        rehypeAutolinkHeadings,
        {
          behavior: "wrap",
          properties: { className: ["group", "no-underline"] },
        },
      ],
      [
        rehypePrettyCode,
        {
          theme: { dark: "github-dark", light: "github-light" },
          keepBackground: false,
        },
      ],
    ],
  },
};
